import express from 'express';
import { conversationalSearch } from '../services/conversationalSearchService.js';
import { isDoctorLinkedToPatient } from '../services/doctorAuthService.js';
import { clearSession } from '../langchain/sessionStore.js';
import { requireAuth } from '../middleware/auth.js';

const router = express.Router();

const MAX_QUERY_LENGTH = 2000;
// session_id is generated by the frontend (e.g. crypto.randomUUID()). It is
// only ever used as an opaque map key, but it is still validated to keep
// junk (or something huge) out of the store.
const SESSION_ID_PATTERN = /^[A-Za-z0-9_-]{8,128}$/;

/**
 * POST /api/search/chat
 * Body: { query: string, session_id: string, patient_user_id?: string }
 *
 * NOTE ON user_id: the brief specified user_id in the request body, but
 * that is deliberately NOT accepted here — it is read from the verified JWT
 * (req.user.userId), exactly as POST /api/search does. Trusting a
 * body-supplied user_id would let any authenticated client search another
 * patient's records by sending someone else's id, which is precisely the
 * cross-user leak this feature is required to prevent. Any user_id sent in
 * the body is ignored.
 *
 * patient_user_id is the ONE exception, and only for doctors: it lets a
 * doctor ask about a specific linked patient's records instead of their
 * own. It is verified against the doctor_patient table on every request
 * (never cached, never trusted on its own) — a doctor with no link to that
 * patient gets 403, same as the main backend's linking flow requires.
 */
router.post('/', requireAuth, async (req, res) => {
  const { query, session_id: sessionId, patient_user_id: patientUserId } = req.body || {};
  const callerId = req.user.userId;

  if (!query || typeof query !== 'string' || !query.trim()) {
    return res.status(400).json({ error: 'query (non-empty string) is required' });
  }
  if (query.length > MAX_QUERY_LENGTH) {
    return res.status(400).json({ error: `query must be ${MAX_QUERY_LENGTH} characters or fewer` });
  }
  if (!sessionId || typeof sessionId !== 'string' || !SESSION_ID_PATTERN.test(sessionId)) {
    return res.status(400).json({
      error: 'session_id is required (8-128 chars, letters/numbers/hyphen/underscore)',
    });
  }
  if (patientUserId !== undefined && (typeof patientUserId !== 'string' || !patientUserId.trim())) {
    return res.status(400).json({ error: 'patient_user_id must be a non-empty string if provided' });
  }

  // Default: search the caller's own records (unchanged behaviour). Only
  // when patient_user_id is supplied AND the link is verified does the
  // scope switch to that patient's data.
  let targetUserId = callerId;

  if (patientUserId) {
    let linked;
    try {
      linked = await isDoctorLinkedToPatient(callerId, patientUserId.trim());
    } catch (err) {
      console.error(`[POST /api/search/chat] link check failed for doctor ${callerId}:`, err);
      return res.status(500).json({ error: 'Could not verify patient access. Please try again.' });
    }

    if (!linked) {
      console.warn(
        `[POST /api/search/chat] user ${callerId} requested patient ${patientUserId} with no doctor_patient link`
      );
      return res.status(403).json({ error: 'You are not linked to this patient.' });
    }

    targetUserId = patientUserId.trim();
  }

  try {
    const result = await conversationalSearch({ query, userId: targetUserId, sessionId });
    return res.status(200).json({
      answer: result.answer,
      structured: result.structured,
      sources: result.sources,
      noResultsFound: result.noResultsFound,
      session_id: result.sessionId,
    });
  } catch (err) {
    // A session_id belonging to another user/patient scope is a client
    // error (and a signal worth logging loudly), not a server fault.
    if (err.message?.includes('belongs to a different user')) {
      console.warn(
        `[POST /api/search/chat] user ${callerId} attempted to use session ${sessionId} scoped to a different patient`
      );
      return res.status(403).json({ error: 'This conversation belongs to a different patient or account.' });
    }

    console.error(
      `[POST /api/search/chat] failed for caller ${callerId}, target ${targetUserId}, session ${sessionId}, query="${query}":`,
      err
    );
    return res.status(500).json({
      error: 'Search failed. Please try again; if this persists, contact support.',
    });
  }
});

/**
 * DELETE /api/search/chat/:session_id
 * Body (optional): { patient_user_id?: string }
 * Clears a conversation so a doctor can start fresh on another patient
 * without earlier context leaking into the new thread.
 *
 * A session created with patient_user_id is stored keyed by that patient's
 * id (see conversationalSearch -> sessionStore), so clearing it must be
 * asked for with the same patient_user_id the doctor used to create it —
 * otherwise this just looks like clearing the doctor's own (empty) session
 * and the real one keeps its history.
 */
router.delete('/:session_id', requireAuth, async (req, res) => {
  const sessionId = req.params.session_id;
  const callerId = req.user.userId;
  const patientUserId = req.body?.patient_user_id;

  if (!SESSION_ID_PATTERN.test(sessionId)) {
    return res.status(400).json({ error: 'invalid session_id' });
  }
  if (patientUserId !== undefined && (typeof patientUserId !== 'string' || !patientUserId.trim())) {
    return res.status(400).json({ error: 'patient_user_id must be a non-empty string if provided' });
  }

  // No link re-check needed here: clearSession already refuses to touch a
  // session unless it was created under this exact scope id, so a doctor
  // guessing at another patient's id gets the same 403 as sessionStore's
  // normal cross-user protection — no separate authorization query needed
  // just to delete memory.
  const scopeId = patientUserId ? patientUserId.trim() : callerId;

  try {
    const existed = await clearSession(sessionId, scopeId);
    // Idempotent: clearing an unknown/already-cleared session is a success,
    // so the frontend can fire this on "new chat" without special-casing.
    return res.status(200).json({ cleared: existed, session_id: sessionId });
  } catch (err) {
    if (err.message?.includes('belongs to a different user')) {
      console.warn(
        `[DELETE /api/search/chat] user ${callerId} attempted to clear session ${sessionId} outside its scope`
      );
      return res.status(403).json({ error: 'This conversation belongs to a different patient or account.' });
    }
    console.error(`[DELETE /api/search/chat] failed for session ${sessionId}:`, err);
    return res.status(500).json({ error: 'Failed to clear conversation.' });
  }
});

export default router;
