-- Migration: create report_embeddings table for RAG semantic search over report notes.
-- Requires the pgvector extension.
--
-- NOTE: user_id and report_id types below assume `reports.id` is bigint and
-- `reports.user_id` is a string (matches backend/db/reports.js). If your
-- actual `reports` table uses a uuid PK, change report_id to uuid before
-- running this.

create extension if not exists vector;

create table if not exists public.report_embeddings (
  id bigint generated by default as identity not null,
  report_id bigint not null,
  user_id character varying not null,
  chunk_text text not null,
  embedding vector(768) not null,
  chunk_index integer not null,
  created_at timestamp with time zone not null default now(),
  constraint report_embeddings_pkey primary key (id),
  constraint report_embeddings_report_id_fkey
    foreign key (report_id) references public.reports (id) on delete cascade,
  -- One row per (report_id, chunk_index): re-processing a report upserts
  -- existing chunks instead of duplicating them.
  constraint report_embeddings_report_chunk_unique unique (report_id, chunk_index)
);

-- Fast filtering by patient before/along with the vector search. Every query
-- MUST include a user_id filter, so this index is on the hot path.
create index if not exists report_embeddings_user_id_idx
  on public.report_embeddings (user_id);

create index if not exists report_embeddings_report_id_idx
  on public.report_embeddings (report_id);

-- Approximate nearest-neighbour index for cosine similarity search.
-- HNSW is used over IVFFlat: it needs no training/list-count tuning as the
-- table grows and gives better recall/latency for the read-heavy pattern
-- here (many searches per patient, occasional writes on report save).
create index if not exists report_embeddings_embedding_hnsw_idx
  on public.report_embeddings
  using hnsw (embedding vector_cosine_ops);
