-- Baseline: report_embeddings table + patient_id btree index.
--
-- report_embeddings has existed and been in active use since before this
-- repo adopted tracked migrations (its original definition lived in an
-- untracked rag/migrations/001_create_report_embeddings.sql, referenced in
-- comments elsewhere in this repo — e.g. supabase/migrations/
-- 20260819175712_rename_user_id_add_foreign_keys.sql's note "report_embeddings
-- already has a user_id index from rag/migrations/001" — but that file is
-- not present in this working tree). README.md's schema-reference block
-- (~lines 207-219) is the only place its DDL survives verbatim, reconstructed
-- from a pg_dump capture. This migration exists purely to give that DDL a
-- tracked home, so a fresh project can be bootstrapped from `supabase
-- migration up` alone instead of hand-copying README SQL.
--
-- Every statement uses IF NOT EXISTS: against the live database (where this
-- table has existed all along) this is a no-op; it only does real work
-- when bootstrapping a fresh project that has never seen it.
--
-- NOTE: the embedding column here is a plain VECTOR(768) with no vector
-- index — the HNSW index this table used to carry
-- (report_embeddings_embedding_hnsw_idx) is intentionally NOT created here.
-- See the very next migration (20260930051112) for why, and README.md's
-- "Database & Vector Storage" section for the current retrieval design.

create extension if not exists vector;

create table if not exists public.report_embeddings (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  patient_id varchar not null references public.patients(id) on delete cascade,
  chunk_text text not null,
  embedding vector(768) not null,
  chunk_index int not null,
  created_at timestamp with time zone default now(),
  constraint report_embeddings_report_chunk_unique unique (report_id, chunk_index)
);

create index if not exists report_embeddings_user_id_idx on public.report_embeddings (patient_id);

-- ═══════════════════════════════════════════════════════════════════════
-- REVERT (run manually if needed — only meaningful on a project bootstrapped
-- from this migration; do NOT run against the live database, since
-- report_embeddings predates this migration there and dropping it would
-- destroy every patient's search index):
--   drop index if exists report_embeddings_user_id_idx;
--   drop table if exists public.report_embeddings;
-- ═══════════════════════════════════════════════════════════════════════
